[workspace]
resolver = "2"
package.edition = "2021"

members = [
  "crates/launchers/metar_data_processor",
  "crates/launchers/standalone_http_server",
  "crates/proxy_application",
]

[workspace.dependencies]
tokio = { version = "1.36.0", features = ["full"] }
